remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Bitcoin Core course"
description: "An in person course on how to contribute to Bitcoin Core."
social:
    name: Sjors provoost
    links: https://twitter.com/provoost
production_url: https://learnbitcoincore.com
github:
  is_project_page: false